server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://106.54.187.182:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
logging:
  file: /var/log/userService/hello-word.log
  level:
    com:
      neo:
        mapper: debug